spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: normal_user
    password: pass
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres